# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy package files and tsconfig.json
COPY package.json package-lock.json tsconfig.json ./

# Copy source files needed for build
COPY src/ ./src/

# Install dependencies without running prepare scripts
RUN npm ci --ignore-scripts

# Build the project
RUN npm run build

# Copy remaining files (entrypoint, etc.)
COPY . .

# Ensure entrypoint.sh is executable
RUN chmod +x entrypoint.sh

# Expose port if necessary (uncomment if required)
# EXPOSE 3000

# Start the MCP server: entrypoint.sh starts Ollama and then the server
CMD [ "sh", "-c", "sh entrypoint.sh & node build/index.js" ]
