version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    container_name: qdrant
    volumes:
      - storage:/qdrant/storage
      - config:/qdrant/config
    command:
      ["sh", "-c", "chown -R 1000:1000 /qdrant/storage && /qdrant/qdrant"]
    environment:
      - QDRANT_ALLOW_RECOVERY=true
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # GRPC API
    expose:
      - 6333
      - 6334
      - 6335

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    expose:
      - 11434
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    command: ["/entrypoint.sh"]
    environment:
      - MODEL=nomic-embed-text
    entrypoint: ["/entrypoint.sh"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "bash",
          "-c",
          "{ printf >&3 'GET / HTTP/1.0\\r\\n\\r\\n'; cat <&3; } 3<>/dev/tcp/localhost/11434 | grep 'Ollama is' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  storage:
  config:
  ollama:
